### ISSUE TITLE
[Idea] Strip comments ?

### ISSUE THREAD

**Issue by kornysietsma** [XAMPPRocky/tokei#335]
It would be handy if there were some way to use the language parsing logic to strip comments from source code - similar to `cloc`'s `--strip-comments` command.  

I'm writing some tools that process source code in language-agnostic ways - things like measuring indentation stats and similar - and I'd love to be able to use the parsers here to ignore comments before I do any processing.  But at the moment it looks like I'd have to duplicate most of `LanguageType::parse_lines` to do this.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I don't think this kind of functionality should be in tokei itself, not least because the way tokei is currently designed, no file contents are stored after processing. So tokei would have to first change this before it could provide a way to strip comments. I think this would be better as a library so that it could be used for different tools.
