### ISSUE TITLE
Windows Binaries Missing

### ISSUE THREAD

**Issue by cwfitzgerald** [XAMPPRocky/tokei#354]
It appears that after version 9.1.0, windows binaries are no longer being built automatically.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Yes that's partially correct as `curl-sys` hasn't compiled on Windows since that time. the dependency on `curl-sys` comes from depending on the git library for testing tokei's gitignore functionality. I haven't found the time to make a decision on how to solve this problem. I'll try ensure the next release brings back at least the MSVC executables, as the tests continue to work on that target, and I believe most people would chose MSVC over GNU anyway.

**Comment by cwfitzgerald** [comment]
Thanks for the prompt response! I definitely agree that the MSVC executables would be enough. It didn't end up being a problem as I just handed the person I was showing tokei to my executable (as I build from cargo [also yay static executables :smile:]), but it would be nice to have in the future. 

Thanks for your work on this wonderful tool!

**Comment by ferdiozturk** [comment]
Sorry to be a PITA, but I just wanted to kindly ask if there is any progress with the MSVC binaries? We love tokei and it is just sad when it is not available for Win...

**Comment by XAMPPRocky** [comment]
I've now fixed the CI issues with deployment and with 10.1.2 there are now prebuilt windows binaries again.

**Comment by ferdiozturk** [comment]
Thank you. Just tested, and it works. When I used tokei back in the day (two years ago) I could easily output to JSON format without problems, as this feature was baked-in obviously... Now it seems I have to install serialization features per "cargo install" with the new version. I have no experience with cargo and how it would work on Win OS.

If you were so kind, could you please release the Win binary with integrated serialization support again? Thxs!

**Comment by XAMPPRocky** [comment]
@ferdiozturk Ah, sorry I'm not deploying the full featured binaries, I'll update that now, and re-release.

**Comment by XAMPPRocky** [comment]
@ferdiozturk Okay, they should include outputting to JSON.

**Comment by io-canopy** [comment]
Seems there's no binaries again.
