### ISSUE TITLE
Add Coloured Output

### ISSUE THREAD

**Issue by jamart28** [XAMPPRocky/tokei#419]
This would be purely enhancement, but I would like a little color or extra formatting in the terminal output. I find it helps with looking quickly through an output personally. I'm not too sure exactly how I would color it. Possibly coloring the lines between the words and the lines different colors. Additionally, bolding the columns headers and languages.

**Comment by XAMPPRocky** [comment]
Hey, thank you for your issue! I would totally approve such a change, however there are few considerations I want to check first. Mainly how does the coloured output look in a dark themed terminal versus a light themed terminal. It should be clear and not hard to read for both themes. I'd also want to use a third party crate to manage this rather than building bespoke functionality, I know there are quite a few crates that support outputting colours. My priority would be on something that is as low impact to the codebase as possible.

**Comment by LovecraftianHorror** [comment]
Hello, I'd like to take on the feature request if you don't mind. I figured that the functionality could be controlled with a `--color (always|auto|never)` flag that seems common from some other programs (`ripgrep`, `fd`, `bat`). Using something like [`colored`](https://crates.io/crates/colored) provides a lot of the functionality we would need while automatically respecting user preferences like [`NO_COLOR`](https://no-color.org/).

My only question would be what color scheme to go with. I think bolding the headers and totals at the bottom is a good start. Beyond that coloring could depend on common file functions (similar idea to how [`exa`](https://crates.io/crates/exa) colors things) such as programming for rust, python, c, etc. config for json, yaml, toml, etc. text for txt, markdown, latex, etc. although I doubt `tokei` already tries to categorize files like this, so it may be more of a significant change to achieve this effect. For a simpler option, different colors could be picked just as static choices or maybe depending on criteria like how large of a portion they take up of the total line count or something similar.

Overall I'd really like to get some more input about peoples' preferences before trying to go any further.

**Comment by XAMPPRocky** [comment]
@LovecraftianHorror Thank you for your interest! Right now without testing, I'm initially inclined to say that `tokei`'s use of actual colour should be minimal to none. I don't see a way in colored to detect the current theme so I'm still concerned about adding some that will look bad against a light or dark theme. However I think experimenting with emphasis (bolding, dimming, italics) is probably the way to go, as `tokei` can have something that looks good on all themes without worrying. Currently I'm thinking the thick rows `===` should be bold and the thin rows `---` dimmed, beyond that I haven't thought much about how should look.

**Comment by LovecraftianHorror** [comment]
I can understand wanting to make sure that the output is still readable for everyone, but from my understanding `colored` uses the user's terminal emulator colors (so in a sense it uses the current theme by default), so if it is unreadable then it's likely the fault of the user's color selection instead of `tokei`'s.

Beyond that, if people don't want color at all then they can set `NO_COLOR` and if they don't want `tokei` specifically to use color then they can `alias tokei='tokei --color never'`. If you're still concerned about usability though then I'd be fine with just using bold, dim, and italics, but providing a flag and respecting `CLICOLOR`, `CLICOLOR_FORCE`, and `NO_COLOR` should give a lot of flexibility to the user still.
