### ISSUE TITLE
Vue: Javascript and CSS comments should be counted as comments instead of code

### ISSUE THREAD

**Issue by DragonI** [XAMPPRocky/tokei#488]
A Vue file may contain HTML, JS and CSS. Version 11 is only handling HTML comments. CSS and JS single line "//" and multi-line ["/*", "*/"] comments are not.  See below.

**Simple Vue component file**

```
<template>
  <!-- HTML comment -->
  <audio ref="audioFile" class="audio-deaf">
    <source
      :src="file"
      :type="type"
    >
    Your browser does not support the audio element.
  </audio>
</template>

<script>
/**
 * JSDoc comment
 */
export default {
  name: 'SlAudio',

  props: {
    /*
     * JS multi-line comment
     */
    file: {
      type: String,
      required: required
    },

    type: {
      type: String,
      required: false,
      default: 'audio/mp3'
    },

    show: {
      type: Boolean,
      required: false,
      default: false
    }
  },

  watch: {
    show: {
      handler (val) {
        if (val) {
          this.play()
        }
      }
    }
  },

  methods: {
    // single line comment
    play () {
      this.$emit('playing')
      this.$refs.audioFile.play()
    }
  }
}
</script>

<style lang="scss" scoped>
  // CSS comment
  .audio-deaf {
    margin-top: 20px;
  }
</style>

```

**v11 result**

```
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Vue                     1           66           58            1            7
-------------------------------------------------------------------------------
 Total                   1           66           58            1            7
```

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This is a known limitation of tokei where it does not correctly handle files that contain multiple languages. I don't know if this will ever be fixed, because frankly I haven't thought of a nice way to handle that corner case. I will try to think about it more, as enough people seem to be interested in this feature (languages in languages).

**Comment by DragonI** [comment]
Hi.

"languages in languages" would be a major undertaking. What about keeping it simple? **No "languages in languages"**.

Instead, all HTML, JS and CSS code is counted as Vue code and comments are counted as comments. Not sure if it's as easy as this. But based on [languages.json](https://github.com/XAMPPRocky/tokei/blob/master/languages.json#L1167), add "line_comment" and modify "multi_line_comments" as below.

```
"line_comment": ["//"],
"multi_line_comments": [["<!--", "-->"],["/*", "*/"]],
```

New Vue config

```
"Vue": {
  "name": "Vue",
  "line_comment": ["//"],
  "multi_line_comments": [["<!--", "-->"],["/*", "*/"]],
  "quotes": [["\\\"", "\\\""], ["'", "'"]],
  "quotes": [["\\\"", "\\\""], ["'", "'"], ["`", "`"]],
  "extensions": ["vue"]
},
```

Result - manually counted comments ;)

```
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Vue                     1           66           50            9            7
```

**Comment by XAMPPRocky** [comment]
@DragonI That sounds like a reasonable compromise to me to in the short term. Your config is almost correct, you just have to merge the two `quotes` properties you have.

**Comment by DragonI** [comment]
Thx. My bad ;)

**Comment by NickHackman** [comment]
This also applies to `HTML`, in addition to Vue and Svelte. I've put some thought into this and think I have an idea for a solution.

Add an additional field to the `languages.json` that adds possible contexts opening and closing and corresponding languages.

For instance, HTML would look like

```json
{
  "Html": {
    "name": "HTML",
    "multi_line_comments": [["<!--", "-->"]],
    "quotes": [["\\\"", "\\\""], ["'", "'"]],
    "extensions": ["html", "htm"],
    "contexts": [
      {"open": "<script>", "close": "</script>", "language": "javascript"},
      {"open": "<style>", "close": "</style>", "langauge": "CSS"}
    ]
  }
}
```
The open script tag here should probably be `<script.*>`

```rust
struct SharedMatchers {
	// ...
	contexts: &'static [&'static Context], // this could be a tuple instead
}

struct Context {
	open: &'static str,
	close: &'static str,
	language: LanguageType,
}
```

in `parse_lines` any place where it could be code, should be checked if it's a context changer, this will add a small overhead for the few languages that have different contexts. `parse_from_slice` would also return a container of Stats rather than solely a Stats. I think this solution is pretty straightforward and is basically what V8 does when parsing HTML. 

The same concept applies to `Vue`, but I think there would be 3 contexts, `<template>`, `<script>` and `<style>`. These would be separate checks, at least in `Svelte` the `<style>` tags allow for specifying a different language like `scss` via `<style type="text/scss">`, for any edge case where the comments and quotes don't behave the same.

What are your thoughts @XAMPPRocky? :slightly_smiling_face:

This would also allow for Tokei to parse interesting blocks separately. For example Rust's unsafe blocks, which could be an interesting feature.

**Comment by XAMPPRocky** [comment]
@NickHackman That's definitely an interesting approach, though I am kinda interested in supporting `type=""` more generally as being able to detect language from MIME type would be a good feature for tokei as a library. I'm going to close this as the original issue has been resolved and we continue the discussion of a more general feature in #536

**Comment by DragonI** [comment]
Just upgraded to version 12. Mind blown. 🙇‍♂️ Kyoshi (教士) @XAMPPRocky
