### ISSUE TITLE
Handle container languages

### ISSUE THREAD

**Issue by XAMPPRocky** [XAMPPRocky/tokei#536]
Aka languages that often contain other languages such as HTML or Vue.

**Comment by NickHackman** [comment]
I think the context approach is the most straightforward, I admit though it is very much so catered towards `HTML`, `Vue`, and `Svelte` because I don't know of any other language that contains other languages.

My idea mentioned in #488 was to essentially follow what V8 and Spidermonkey have to do when they interpret `HTML`. I think that idea could be expanded further to include MIME types via the `type` attribute on `<script>` tags and possibly in other languages? if applicable.


```json
{
  "Html": {
    "name": "HTML",
    "multi_line_comments": [["<!--", "-->"]],
    "quotes": [["\\\"", "\\\""], ["'", "'"]],
    "extensions": ["html", "htm"],
    "contexts": [
      {"open": "<script {{type}}>", "close": "</script>", "types": [["type=\\\"text/javascript\\\"", "JavaScript"]]},
      {"open": "<style>", "close": "</style>", "langauge": "CSS"}
    ]
  }
}
```

Where at compile time we use handlebars to inject all possible types into the opening/closing section in order to handle different languages.

We'd also have to handle other possible attributes inside of opening/closing tags, like `defer` which prevents just using `find` :slightly_frowning_face:

**Comment by XAMPPRocky** [comment]
@NickHackman I was thinking that the HTML case is actually common enough to warrant a better level of support. I haven't thought much about how this would look like on Rust side but ideally it would look something like this.

```json5
{
  "Html": {
    "name": "HTML",
    "multi_line_comments": [["<!--", "-->"]],
    "quotes": [["\\\"", "\\\""], ["'", "'"]],
    "extensions": ["html", "htm"],
    "contexts": [
      // htmlalike would trigger a code path for HTML parsing
      { "tag": "script",  "default": "JavaScript", "htmlalike": true },
      { "tag": "style",  "default": "Css", "htmlalike": true }
    ]
  },
  // ...
  "JavaScript": {
    // …
    "mime": ["text/javascript"]
  }
}
```

**Comment by NickHackman** [comment]
That looks way cleaner, I really like that syntax and better support for HTML-esque languages. It also makes handling many `mime` types easier :+1: 

In regards to the Rust side

- A couple of new functions in `language_type`
- Keep track of current context in `SyntaxCounter`
- Add `parse_context` to `SyntaxCounter`
	- handle `htmlalike` differently and ignore other attributes
- Add field for context in `SharedMatcher`
- Anywhere it's code we check if the context changes iff the language has contexts
- Return probably a `Vec` or a `BtreeMap`? from all the `parse_*` methods
- Further upward integration should be pretty straightforward

I think that's roughly it right? Probably missing a thing or two though.

**Comment by XAMPPRocky** [comment]
That's definitely the happy path, but there are quite few details that need to be figured out.

- Are there other container languages that aren't HTML/XML based that I would want to support, even if it's not as smart as HTML/XML equivalents?
- I wouldn't want to return a `Vec` or `BTreeMap` of languages, both because that would be a breaking change, and I'm not sure it fits with the conceptual of how Tokei works.
- Related to that, one of the biggest considerations is how tokei *the application* displays this information in the CLI interface. Because I don't think the correct approach is to just collate them into a flat list of languages.

**Comment by NickHackman** [comment]
> I wouldn't want to return a Vec or BTreeMap of languages, both because that would be a breaking change, and I'm not sure it fits with the conceptual of how Tokei works.

Agreed, I don't think we can prevent this from being a breaking change. I think changing the `Stats` object in order to accommodate multiple languages would be the least bad breaking change. Maybe a `FileStats`?

> Because I don't think the correct approach is to just collate them into the flat list of languages that is the current UI.

I don't think its too bad. I agree that there's probably a better way to display the information, but as of right now I don't know what that would look like. I imagine it would be more complicated than currently and I like the current simplicity.

**Comment by XAMPPRocky** [comment]
> I don't think its too bad. I agree that there's probably a better way to display the information, but as of right now I don't know what that would look like. I imagine it would be more complicated than currently and I like the current simplicity.

I do have a "mind's eye" of how it could look, as I've thinking about this feature for awhile, but I need to make a proof of concept to see if it's actually any good.

**Comment by buttaface** [comment]
It would be nice if patch/diff files are handled, they're currently ignored:
```
WARN  tokei::language::language_type] Unknown extension: patch
```

**Comment by NickHackman** [comment]
@buttaface I personally would like Tokei to support diffs/patches!

Tokei would have to treat diffs and patches as an edge case when parsing, in `LanguageType::parse_lines` an additional check (like the one currently for Fortran) would have to be done to trim off the leading `+` and `-`.

In order to get the file type we just look at the lines starting with `+++` and `---` and try to guess the language based on extension. We could try to find the file if that fails, but that sounds expensive.

```diff
From 3a16816a6f5d38014c2a06ce395873c545c8789a Mon Sep 17 00:00:00 2001
From: Soenke Lambert <s.lambert@mittwald.de>
Date: Tue, 12 Nov 2019 10:44:02 +0100
Subject: [PATCH] Fullscreen current window with [Alt]+[Shift]+[f]

This actually fullscreens a window, instead of just hiding the statusbar
and applying the monocle layout.
---
 config.def.h | 1 +
 dwm.c        | 8 ++++++++
 2 files changed, 9 insertions(+)

diff --git a/config.def.h b/config.def.h
index 1c0b587..8cd3204 100644
--- a/config.def.h
+++ b/config.def.h
@@ -78,6 +78,7 @@ static Key keys[] = {
 	{ MODKEY,                       XK_m,      setlayout,      {.v = &layouts[2]} },
 	{ MODKEY,                       XK_space,  setlayout,      {0} },
 	{ MODKEY|ShiftMask,             XK_space,  togglefloating, {0} },
+	{ MODKEY|ShiftMask,             XK_f,      togglefullscr,  {0} },
 	{ MODKEY,                       XK_0,      view,           {.ui = ~0 } },
 	{ MODKEY|ShiftMask,             XK_0,      tag,            {.ui = ~0 } },
 	{ MODKEY,                       XK_comma,  focusmon,       {.i = -1 } },
diff --git a/dwm.c b/dwm.c
index 4465af1..c1b899a 100644
--- a/dwm.c
+++ b/dwm.c
@@ -211,6 +211,7 @@ static void tagmon(const Arg *arg);
 static void tile(Monitor *);
 static void togglebar(const Arg *arg);
 static void togglefloating(const Arg *arg);
+static void togglefullscr(const Arg *arg);
 static void toggletag(const Arg *arg);
 static void toggleview(const Arg *arg);
 static void unfocus(Client *c, int setfocus);
@@ -1719,6 +1720,13 @@ togglefloating(const Arg *arg)
 	arrange(selmon);
 }
 
+void
+togglefullscr(const Arg *arg)
+{
+  if(selmon->sel)
+    setfullscreen(selmon->sel, !selmon->sel->isfullscreen);
+}
+
 void
 toggletag(const Arg *arg)
 {
-- 
2.17.1
```
Diff from Dwm just for a concrete example. I'm guessing here we'd treat all lines like `Date: .+` as code, and really just count comments in the legitimate code as comments.

**Comment by XAMPPRocky** [comment]
If people are interested I have just put up a working version of this feature onto master, and soon plan to release once I've polished up the last aspects of it.
