### ISSUE TITLE
support of q and k files

### ISSUE THREAD

**Issue by BodonFerenc** [XAMPPRocky/tokei#537]
Hi All,

can you add support for kdb+/q and k files? The extensions are .q and .k respectively. More information about kdb+ is at https://code.kx.com/q/

Thanks!
Ferenc

**Comment by XAMPPRocky** [comment]
Thank you for your issue! If you want a language added the best way to do is to add it is to create pull request updating the`languages.json`, and add test files for the language. You can look at #532 as an example and the [contributing.md](./contributing.md) for how to add the language.

**Comment by jmesheridan** [comment]
I've looked at adding the above languages but am running into an issue.

Both languages utilise the same character to denote a single comment and a multi_line_comment, only differentiating based on the characters that follow.

Is this currently supported? 

`/ 8 lines 2 code 6 comments `
`/`
`A line with a solitary "/" marks the beginning of a multiline comment. `
`A multiline comment is terminated by a solitary "\".`
`\`
`codeLine1:1+2`
`/ This should act as a single comment due to characters following "/" on the same line.`
`codeLine2:1+3`

**Comment by XAMPPRocky** [comment]
@jmesheridan Not currently I believe :(
