### ISSUE TITLE
Infinite loop on some encodings

### ISSUE THREAD

**Issue by shachaf** [XAMPPRocky/tokei#616]
I tried running tokei (12.0.4) on a directory with a bunch of source in it and it went into an infinite loop. I tried to track it down a bit and it looks like it's related to Firefox encoding tests.

Here are some files it failed on (you can download the raw file from these pages to test):

* https://searchfox.org/mozilla-central/source/testing/web-platform/tests/encoding/legacy-mb-japanese/shift_jis/sjis_chars-csshiftjis.html
* https://searchfox.org/mozilla-central/source/testing/web-platform/tests/encoding/legacy-mb-korean/euc-kr/euckr_chars-cseuckr.html
* https://searchfox.org/mozilla-central/source/testing/web-platform/tests/encoding/legacy-mb-tchinese/big5/big5_chars-big5-hkscs.html

There are also others. I suggest downloading the Firefox code and running tokei on it to verify.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I'll try to look into this over the week.

**Comment by cmdcolin** [comment]
I am just gonna guess really randomly but running tokei on https://github.com/nodejs/node appears to never finish (certainly, other large repositories are almost instant) so might run into this

**Comment by XAMPPRocky** [comment]
@cmdcolin Thank you for the info! If you could help by finding a file in the repo causing that, I can use that for a test case.

**Comment by shachaf** [comment]
In the linked node case it looks like it's the files in https://github.com/nodejs/node/tree/master/test/fixtures/wpt/encoding, which seems to have some of the same test files as Firefox (legacy-mb-japanese etc.). But if this is happening with multiple repositories it would be good to have some way of detecting it!

**Comment by alexmaco** [comment]
I've investigated this issue, and it it looks like:
- the issue is not related to encoding
- it's not an infinite loop, parsing _does_ terminate, it just takes an extremely long time.

It looks like a pathological case of a 600+KiB file (for instance, `eucjp_chars.html` from the firefox tests), with no line separators, containing a language that allows for embedding other languages (html in this case).

The problem is that embedding detection relies on running some regexes to search for textual markers on the current line. This is done fairly frequently, almost on every byte (outside of strings), Since the file is a single line, we have 2 regexes essentially searching the entire remainder of the file after every byte is parsed.
See https://github.com/XAMPPRocky/tokei/blob/0751e3bb830614e671b0baa750c38cb9b9946ee1/src/language/syntax.rs#L440-L455

@XAMPPRocky for an efficient fix, parsing would have to be changed significantly, to avoid running each regex more than once per non-string buffer segment. Do you maybe have any implementation insight that will make this simpler that the obvious approach ?

**Comment by XAMPPRocky** [comment]
@alexmaco Thank you for your investigation and sorry for the late reply, I've been busy at work. Your investigation looks correct to me, and I do think the correct solution is to stop performing it on each byte, and instead try to reduce it to once per line in the best case, and as needed in the worse case.

I haven't verified that this will work but from reviewing the code, I think what should occur is running the "start of" multi line blocks analysis once per line caching the offsets found by the regex, and then if the state machine ends up past it because it ended up being inside a string or comment, we re-run the find start of method.

**Comment by alexmaco** [comment]
> I haven't verified that this will work but from reviewing the code, I think what should occur is running the "start of" multi line blocks analysis once per line caching the offsets found by the regex, and then if the state machine ends up past it because it ended up being inside a string or comment, we re-run the find start of method.

I've implemented the regex result caching and it works really well. Only problem is that running the new code results in slightly different final stats (I've run into #711 investigating some of these issues). I'll post a PR with the regex caching once I'm able to sort those differences out.
