### ISSUE TITLE
Have a question for tokei to count total lines

### ISSUE THREAD

**Issue by HaojunRen** [XAMPPRocky/tokei#775]
I want to know tokei to calculate github repository code lines, only to master branch or all branches?
For example, tokei show my respository(has 3 branches) with 10000 lines, that 10000 lines means master branch, or all 3 branches? Thanks a lot

**Comment by brightly-salty** [comment]
I think that would be the master branch. You can verify this by running `tokei` on a local clone of your master branch and making sure the numbers are the same.

**Comment by miraclx** [comment]
I suppose you mean `tokei_rs`?

If that's the case, then, yes. Behind the scenes, it's a simple `git clone` for your repo and `tokei` gathers statistics for whatever the default branch for your repo is.

Otherwise, if you mean the `tokei` utility itself, it simply counts and displays lines of code of all valid files in current directory.

**Comment by HaojunRen** [comment]
It makes sense. Thanks a lot
