### ISSUE TITLE
Feature Request: Display Unsafe Code Lines and Percentage for Rust Projects

### ISSUE THREAD

**Issue by eval-exec** [XAMPPRocky/tokei#995]
Hello,

I am currently using Tokei for counting code lines in my Rust projects, and I find it to be an excellent tool. However, I noticed that it does not provide any information on unsafe code lines and their percentage in the project. This information is crucial for Rust developers to evaluate the safety of their codebase.

I came across another project called [cargo-count](https://github.com/kbknapp/cargo-count) that can display line counts of source code in projects and includes a naive unsafe counter for Rust source files. I believe incorporating a similar feature into Tokei would greatly benefit Rust developers who use your project.

Feature Request:
- Add functionality to display the number of unsafe code lines in Rust projects
- Calculate the percentage of unsafe code lines relative to the total code lines

This enhancement would provide a more comprehensive overview of the codebase and help developers identify areas of their code that may require attention for safety improvements.

I appreciate your consideration of this feature request, and I am looking forward to seeing how Tokei evolves to better support Rust developers.

Thank you for your time and efforts in maintaining this great tool.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However right now I don't think this is a feature I would add to tokei, for a couple of reasons.

- It require parsing and understanding more Rust code than tokei currently does, tokei is pretty general and I only tend to add features that could benefit multiple languages.
- Even with that level of parsing it would still not be fully accurate, things like macros can conceal the presence of unsafe code from a parser, to properly count every line, you'd need to make sure you're generating all of the code ahead of time.
- I'm not sure I see strong value in knowing the amount of unsafe code. While you generally want as little unsafe code as possible, most likely the code will end up using an API (e.g. `std`) that internally uses unsafe, and as long as it's correct there's not wrong with `unsafe`, so I would be hesitant to give a statistic that people might misuse or misunderstand.

I think something like cargo-count or https://github.com/rust-secure-code/cargo-geiger are much better alternatives because they can focus on providing accurate stats for Rust projects rather than tokei which is trying to be a general code statistic tool.
